### ISSUE TITLE
7.0 Release Checklist

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#1191]
### Milestone ###

https://github.com/rabbitmq/rabbitmq-dotnet-client/milestone/53

### Checklist ###

* [ ] - No test flakes! (#1193 ahem)
* [ ] - Re-visit target frameworks https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1189
* [ ] - Try to reduce the amount of code in this library. For instance, there seems to be unnecessary interfaces, helper classes, etc. Just setting up a connection allows too many knobs (https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1218)

**Comment by michaelklishin** [comment]
While trying to backport #1202 I have noticed that the delta between `main` and `7.x` is large enough that I wonder if it would make sense to ship `8.0` or `7.0` from `main`.

**Comment by Zerpet** [comment]
@lukebakken do we want to use this issue to keep track of all the changes for 7.0 ? 
I can go through what's pending and update this issue. Asking because we also have the milestone, so we can use either (or both!).

**Comment by lukebakken** [comment]
We should use separate issues and close this. Thanks for noticing.
